### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by dingo-d** [dingo-d/woo-solo-api#107]
- [ ] Update CHANGELOG.md with relevant changes
- [ ] Update Readme.txt and Readme.md files
  - Update all the tags, especially **Stable tag** 
  - Update hooks if added
  - Update FAQ if needed
- [ ] Update main plugin file - all the tags
- [ ] Make sure everything works in the production environment and development environment
- [ ] Make sure plugin translation is working
  - Make sure all strings are translatable, and properly translated
- [ ] Fix all lint issues
- [ ] After all of the above has been fixed tag the new version in the GH
- [ ] Commit the new version to the wordpress.org SVN repo
